name: wishtogether
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core:
  firebase_auth: ^0.20.0+1
  firebase_admob:
  cloud_firestore: ^0.16.0
  firebase_storage: ^7.0.0
  cloud_functions: ^0.9.0
  firebase_messaging: 
  google_sign_in: ^4.5.6
  sign_in_with_apple: ^2.5.4
  provider: ^4.3.2+3
  flutter_spinkit: ^4.1.2
  uuid: ^2.2.2
  intl: ^0.16.1 #Date format
  drag_and_drop_gridview: ^1.0.8
  cupertino_icons: ^0.1.3
  ntp: ^1.0.7 #Accurate DateTime
  flutter_colorpicker: ^0.3.5
  toggle_switch: ^0.1.8


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - assets/google_logo.png

  fonts:
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand_medium.ttf
          weight: 300
    - family: RobotoLight
      fonts:
        - asset: fonts/Roboto-Light.ttf
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf

  uses-material-design: true
