name: wishtogether
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.0.0
  firebase_auth: ^1.0.2
  # firebase_admob: ^0.11.2 #TODO Deprecated
  google_mobile_ads: ^0.13.6
  cloud_firestore: ^1.0.0
  firebase_storage: ^8.0.0
  cloud_functions: ^3.0.6
  firebase_messaging: ^10.0.0 #Check for stable releases
  google_sign_in: ^4.5.9
  sign_in_with_apple: ^3.2.0
  provider: ^6.0.1
  flutter_spinkit: ^5.1.0
  uuid: ^2.2.2
  intl: ^0.17.0 #Date format
  drag_and_drop_gridview: ^1.0.8
  cupertino_icons: ^1.0.3
  ntp: ^2.0.0 #Accurate DateTime
  flutter_colorpicker: ^0.6.0
  toggle_switch: ^1.3.0
  image_picker: ^0.7.5
  path: ^1.7.0
  package_info: ^2.0.2
  carousel_slider: ^4.0.0
  smooth_page_indicator: ^1.0.0+2
  flutter_linkify: ^5.0.0
  url_launcher: ^6.0.2
  fluttertoast: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/android_icon.png"
  image_path_ios: "assets/ios_icon.png"

flutter:

  assets:
    - assets/google_logo.png

  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
          weight: 300
        - asset: fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: fonts/OpenSans-Bold.ttf
          weight: 900
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand_medium.ttf
          weight: 300
    - family: RobotoLight
      fonts:
        - asset: fonts/Roboto-Light.ttf
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf

  uses-material-design: true
